# Generated by Django 5.0.7 on 2024-07-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_terminal', '0002_order_address_order_city_order_country_order_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
